version: '3.9'
services:
  app:
    stdin_open: true
    tty: true
    ports:
      - '3000:3000'
    build:
      dockerfile: Dockerfile.dev
      context: ./app
    volumes:
      - type: bind
        source: ./app
        target: /home/node
      - type: volume
        target: /home/node/node_modules