version: '3.9'
services:
  client:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - type: bind
        source: ./
        target: /home/node
      - type: volume
        target: /home/node/node_modules