version: '3.9'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - type: bind
        source: ./app
        target: /app
      - type: volume
        target: /app/node_modules
  test:
    build: .
    volumes:
      - type: bind
        source: ./app
        target: /app
      - type: volume
        target: /app/node_modules
    tty: true
    stdin_open: true
    command: ["npm", "run", "test"]